---
language: cpp
compiler: gcc
os: linux
sudo: required
dist: trusty
env:
  global:
    - MAKEJOBS=-j3
before_install:
    - sudo apt-get -qq update
#    - sudo apt-get install -y qt5-default qt5-qmake qtbase5-dev-tools qttools5-dev-tools build-essential libboost-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev libssl-dev libdb++-dev libminiupnpc-dev libqt5webkit5-dev

install:
    - sudo apt-get install build-essential
    - mkdir -p $HOME/inputs
    - cd $HOME/inputs && wget --user="$AUTH_USER" --password="$AUTH_PASSWORD" https://deps.shadow.cash/shadow-deps-linux.tar.xz

    - export INDIR=$HOME/inputs
    - export DEPSDIR=$HOME/deps
    - export PATH=$DEPSDIR/host/bin:$PATH

    - mkdir -p $BINDIR $DEPSDIR
    - cd $DEPSDIR && tar xf $INDIR/shadow-deps-linux.tar.xz
script: |
    cd src
    make $MAKEJOBS -f makefile.unix STATIC=1 OPENSSL_INCLUDE_PATH="$DEPSDIR/include" OPENSSL_LIB_PATH="$DEPSDIR/lib" $MAKEOPTS shadowcoind USE_UPNP=1 BOOST_LIB_SUFFIX="-mt" DEBUGFLAGS=
    #install -s shadowcoind $BINDIR/
    cd ..
    qmake INCLUDEPATH="$DEPSDIR/include" LIBS="-L$DEPSDIR/lib" BOOST_LIB_SUFFIX="-mt" RELEASE=1 USE_QRCODE=1

    sed -i 's^,-whole-archive -lleveldb -Wl,^,-lleveldb,^' Makefile
    make $MAKEJOBS
    strip shadow
    #install shadow $BINDIR/
    #cd $BINDIR
    #zip shadow.linux.zip shadow # shadowcoind
#    - qmake
#    - make -j2
#    - cd src && RELEASE=1 STATIC=TRUE make -j2 -f makefile.unix && strip shadowcoind

#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
#  on:
#    tags: true
